### ISSUE TITLE
Error when two Koopa shells collide

### ISSUE THREAD

**Issue by thcheetah777** [mx0c/super-mario-python#71]

**Comment by thcheetah777** [comment]
## The error
Traceback (most recent call last):
  File "main.py", line 46, in <module>
    main()
  File "main.py", line 36, in main
    level.drawLevel(mario.camera)
  File "C:\Users\Leo Feng\Coding\Python\Projects\superMario\classes\Level.py", line 94, in drawLevel
    self.updateEntities(camera)
  File "C:\Users\Leo Feng\Coding\Python\Projects\superMario\classes\Level.py", line 77, in updateEntities
    entity.update(cam)
  File "C:\Users\Leo Feng\Coding\Python\Projects\superMario\entities\Koopa.py", line 40, in update
    self.die(camera)
  File "C:\Users\Leo Feng\Coding\Python\Projects\superMario\entities\Koopa.py", line 64, in die
    self.textPos.y += 0.5
AttributeError: 'Koopa' object has no attribute 'textPos'

**Comment by mx0c** [comment]
@thcheetah777 Could you look into this issue?

**Comment by thcheetah777** [comment]
You mean me?

**Comment by thcheetah777** [comment]
I can do it

**Comment by thcheetah777** [comment]
I did it

**Comment by thcheetah777** [comment]
#81
